# Generated by Django 4.2 on 2023-04-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='enter_at',
            new_name='action_at',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='leave_at',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='action',
            field=models.SmallIntegerField(choices=[(1, 'Enter'), (0, 'Leave')]),
        ),
    ]
