# Generated by Django 4.2 on 2023-04-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_enter_at_attendance_action_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='action_at',
            new_name='enter_at',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='action',
        ),
        migrations.AddField(
            model_name='attendance',
            name='leave_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
