# Generated by Django 4.2 on 2023-04-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_attendance_action_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='action_at',
            field=models.DateTimeField(),
        ),
    ]
