# Generated by Django 4.2 on 2023-04-18 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_action_at_attendance_enter_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='hours',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
