# Generated by Django 4.2 on 2023-04-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_attendance_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
