# Generated by Django 4.2 on 2023-04-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_attendance_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='hours',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
